augmentation:
  degrees: 5.0
  fliplr: 0.5
  flipud: 0.0
  hsv_h: 0.005
  hsv_s: 0.3
  hsv_v: 0.2
  mixup: 0.0
  mosaic: 0.5
  perspective: 0.0
  scale: 0.2
  shear: 1.0
  translate: 0.05
loss:
  box: 7.5
  cls: 0.5
  dfl: 1.5
  focal_loss_gamma: 1.5
  label_smoothing: 0.0
model:
  anchors: null
  depth_multiple: 0.33
  nc: 10
  width_multiple: 0.25
training:
  batch_size: 4
  epochs: 200
  learning_rate: 0.001
  momentum: 0.9
  patience: 20
  save_period: 10
  warmup_epochs: 5
  warmup_momentum: 0.8
  weight_decay: 0.0005
